/**
 * 
 */
package navex.solver;

import java.util.HashSet;
import java.util.List;

import edu.uci.ics.crawler4j.util.IO;
import navex.formula.Formula;

/**
 * @author Abeer Alhuzali
 * this class is used to build formulas from the AST in the Code Property Graph
	 * input is the list of mappings generated a traversal that searches execution traces.
	 * Formula : In file: :login.php, line: 67, id: 60, var: _GET__mode, 
	 * 			map: [mode:_GET__mode, username:_POST__username, passwd:_POST__passwd] )

 * For more information, please read "NAVEX: Precise and Scalable Exploit Generation for Dynamic Web Applications"
 */
public class DynamicSolver {

	
	//Edit this path: This is specific to Navex's evaluation
	//this will extract the TAC formulas generated by a traversal that searches execution traces.

	public static HashSet<Formula> getServerFormula () {

		HashSet<Formula> gf = IO.readGroovyFile("/home/user/navex/formulaMapping.txt");

		return gf;

	}

}
